### ISSUE TITLE
Support times for due dates

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#109]
- Todoman should introduce a `time_format` configuration parameter that, if non-empty, is *additionally* used to format due datetimes. It should be omitted if `DUE` does not have a time component.
- Todoman should prevent people from using `%H`, %M` and so on in `date_format` (I'm currently doing that)
- Likewise it should prevent people from using `%Y` etc in `time_format`

**Comment by hobarrera** [comment]
Okay, so this makes sense. I was actually thinking of additional changes that contribute to this:

1. Make `compact_format` configurable (via the configuration file -- *no cli flag*).
1. Introduce a new `time_format` setting (as you suggested).
1. Change `compact_format` to include separate `due_date` and `due_time` component: `{id:3d} [{completed}] {urgent} {due_date} {due_time} {summary} {list}{percent}`. I'm not sure if I want to change the default or not. What I **am** sure of, is that it'll allow you to retain you current output. 😉 
1. The `"today"/"tomorrow"` thingy will only replace `due_date`, having no effect on the time (we'll probably add `Formatter.parse_time`.
1. Double check how all this affects `--porcelain` (tests will quickly squeal if we break it though).

**Comment by untitaker** [comment]
I'm labelling this `hard` because of the introduction of `compact_format`. I don't think `--porcelain` will be affected by this at all. It ignores all format options.

**Comment by hobarrera** [comment]
I just realized we need to implement this for #108 to work/make sense (for some reason I'd assumed we'd done this already).

**Comment by hobarrera** [comment]
Well, without date/time separation (the suggestion here), the code for #108 won't work, because `format_date` actually receives a datetime object.

**Comment by untitaker** [comment]
#117 fixes this. I chose a route that doesn't implement a config option for `compact_format`. The `dt_separator` is necessary in either case because we need to use it for parsing input as well.
