### ISSUE TITLE
Running ```todo new``` raises exception

### ISSUE THREAD

**Issue by rimshaakhan** [pimutils/todoman#116]
For eg.: if I run ```todo new "Go to Zeba's Birthday Party```, it throws up an error saying:
```
Usage: todo new [OPTIONS] [SUMMARY]...

Error: Invalid value for "--list" / "-l": Personal. Available lists are: 
```

There are no lists available, do I need to create it manually?

**Comment by Swati4star** [comment]
I am also facing same error.

**Comment by untitaker** [comment]
Hello all,

that is indeed something that should be clarified: You need to create task lists yourself. The reason for this is that usually [vdirsyncer](https://github.com/pimutils/vdirsyncer) is supposed to manage task lists at this level.

If you have a configuration like this:

    path = ~/.todo/*

this means that you need to create a folder in `~/.todo/`, and that will be your new tasklist.

Hope that clears the confusion!

**Comment by Swati4star** [comment]
This solves the problem. Thanks :+1:

**Comment by untitaker** [comment]
I'm unsure what to do about this, feel free to open PRs that clarify the docs or improve todoman's UX on this matter. #118 seems like a first step.

**Comment by hobarrera** [comment]
I'm closing this in favour of #118. We'll be improving the error message we display if no lists are available (since this *is* quite counter intuitive/unfriendly).
