### ISSUE TITLE
todo does not output anything when their are no list. 

### ISSUE THREAD

**Issue by AnubhaAgrawal** [pimutils/todoman#118]
**Actual behavior**
When running for the first time or when there are no lists, the `todo` command outputs nothing. This is very counter-intuitive and may confuse the users.
**Expected behavior**
When there are no lists, a warning should be displayed saying the same and a suggestion to display help should be shown.
I would like to work on this issue. Can I send a PR?

**Comment by untitaker** [comment]
This makes sense, and yes, PR is welcome!

I think all that is necessary is a check whether the path is empty, [right here](https://github.com/untitaker/todoman/blob/ba9b8c59b52d25a946d074713b88c309e2d02a5e/todoman/cli.py#L112).

Also a command to show all task lists would probably be useful for debugging.
