### ISSUE TITLE
test default due fails with assertionerror

### ISSUE THREAD

**Issue by cinghiopinghio** [pimutils/todoman#119]
Hi,

In the last update in Archlinux (updating from 2.0.2-1 to 2.1.0-1) I got the following failure while performing the test `test_default_due2`

```
________________________________________________ test_default_due2 _________________________________________________

tmpdir = local('/tmp/pytest-of-XXXXXX/pytest-9/test_default_due20')
runner = <click.testing.CliRunner object at 0x7f9b9d3f4f60>
create = <function create.<locals>.inner at 0x7f9ba0de31e0>
default_database = <todoman.model.Database object at 0x7f9b9d3f4b00>

    @freeze_time(datetime.datetime.now())
    def test_default_due2(tmpdir, runner, create, default_database):
        cfg = tmpdir.join('config')
        cfg.write('default_due = 24\n', 'a')
    
        r = runner.invoke(cli, ['new', '-ldefault', '-dtomorrow', 'aaa'])
>       assert not r.exception
E       assert not InvalidArgsError(<class 'icu.SimpleDateFormat'>, 'format', (FakeDatetime(2003, 10, 30, 11, 45),))
E        +  where InvalidArgsError(<class 'icu.SimpleDateFormat'>, 'format', (FakeDatetime(2003, 10, 30, 11, 45),)) = <Result InvalidArgsError(<class 'icu.SimpleDateFormat'>, 'format', (FakeDatetime(2003, 10, 30, 11, 45),))>.exception

tests/test_basic.py:225: AssertionError
================================== 1 failed, 45 passed, 3 xfailed in 2.71 seconds ==================================
```

I'm not sure what's going wrong, maybe this can be helpful for you.

**Comment by untitaker** [comment]
I can't reproduce this failure when installing `todoman` from AUR.

**Comment by hobarrera** [comment]
Nor can I (I also use arch and actually maintain the AUR package). Can you provide the output of `pip freeze`. Is this the output of `makepkg`, or some helper? Are you using a virtualenv?

**Comment by cinghiopinghio** [comment]
Thanks for the fast reply... I'm installig `todoman` with `pacaur` so yes, it should be the `makepkg` output and no, I'm not using any virtualenv.
Just tried to download the `PKGBUILD` and `makepkg` give me the same failure.

Here I append the output of `pip freeze`:
```
alabaster==0.7.9
ansi==0.1.3
appdirs==1.4.0
arrow==0.10.0
atomicwrites==1.1.5
Babel==2.3.4
Beaker==1.8.1
beautifulsoup4==4.5.3
cffi==1.9.1
chardet==2.3.0
click==6.7
click-log==0.1.8
click-repl==0.1.1
click-threading==0.4.3
colorlog==2.10.0
colour==0.1.2
configobj==5.0.6
cryptography==1.7.2
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
docopt==0.6.2
docutils==0.13.1
easygui===0.98.0-UNRELEASED
file-magic==0.3.0
flake8==3.3.0
freezegun==0.3.8
future==0.16.0
greenlet==0.4.12
httplib2==0.10.3
hypothesis==3.6.1
icalendar==3.11.3
idna==2.2
imagesize==0.7.1
Jinja2==2.9.5
jsonschema==2.6.0
keyutils==0.4
khal==0.9.3.dev24+ngaa986b4
khard==0.11.4
lensfun==0.3.2
louis==3.0.0
lxml==3.7.3
Mako==1.0.6
Markdown==2.6.8
Markups==2.0.0
MarkupSafe==0.23
mccabe==0.6.1
mistune==0.7.3
msgpack-python==0.4.8
nose==1.3.7
notebook==4.3.1
oauthlib==2.0.1
olefile==0.43
opendht==1.2.1
packaging==16.8
pafy==0.5.3.1
parsedatetime==2.2
pew==0.1.26
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
pkginfo==1.4.1
ply==3.10
prompt-toolkit==1.0.13
psutil==5.1.3
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.2.2
pycodestyle==2.3.1
pycparser==2.17
pycrypto==2.6.1
pyenchant==1.6.8
pyflakes==1.5.0
Pygments==2.2.0
pygobject==3.22.0
PyICU==1.9.5
pymediainfo==2.1.5
pyparsing==2.1.10
PyPDF2==1.26.0
PyPrind==2.9.8
pyshp==1.2.10
pytest==3.0.6
pytest-runner==2.11.1
python-dateutil==2.6.0
python-distutils-extra==2.39
python-libtorrent==1.1.1
python-sane==2.8.3
pythonz-bd==1.10.2
pytz==2016.10
pyxdg==0.25
PyYAML==3.12
pyzmq==16.0.2
requests==2.13.0
requests-oauthlib==0.8.0
requests-toolbelt==0.7.1
resumable-urlretrieve==0.1.5
setuptools-scm==1.15.1.dev17+ngb0d17f1
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
sortedcontainers==1.5.7
Sphinx==1.5.2
sphinx-rtd-theme==0.1.9
sphinxcontrib-newsfeed==0.1.4
svgwrite==1.1.10
team==1.0
terminado==0.6
todoman==2.0.2
tornado==4.4.2
traitlets==4.3.1
tzlocal==1.3
urllib3==1.20
urlscan==0.8.3
urwid==1.3.1
vdirsyncer==0.14.1
virtualenv==15.1.0
virtualenv-clone==0.2.6
vobject==0.9.4.1
wcwidth==0.1.7
widgetsnbextension==1.2.6
yapf==0.16.0
```

**Comment by untitaker** [comment]
I don't have `PyICU` installed and I wouldn't know how todoman would depend on it, but it somehow appears in the output of `check()`?

**Comment by cinghiopinghio** [comment]
Indeed I have `python-pyicu` installed which is required by `python-vobject`
which is required by `khard`, I don't know how this affects `todoman`.
Tomorrow I'll try to disintall it temporarily.

**Comment by cinghiopinghio** [comment]
Actually that was the problem. In fact I:

- removed khard and its `python-pyicu` deps
- updated todoman with no issues
- reinstalled khard and its deps

This worked fine but I don't know if any bug is hidden somewhere. If I'll experience some problem I'll get back.

Thanks for the advice.

**Comment by untitaker** [comment]
I could reproduce this by installing `pyicu`. That's pretty nasty.

**Comment by hobarrera** [comment]
Looks like `parsedatetime` uses `pyicu` only if avaiable:

https://github.com/bear/parsedatetime/blob/master/parsedatetime/pdt_locales/__init__.py#L10
https://github.com/bear/parsedatetime/blob/master/parsedatetime/pdt_locales/icu.py#L16

The problem is, it crashes, while _not using it_ does not.

**Comment by cinghiopinghio** [comment]
This seems a bit crazy...
But there seems to be no side effects on the execution... I haven't tested extensively though.

**Comment by hobarrera** [comment]
I *might* fail when trying to create events with something like `todo new --due tomorrow`, but I'm not 100% certain.

**Comment by cinghiopinghio** [comment]
Just tryed: `todo new --due tomorrow buy bread` worked fine

**Comment by hobarrera** [comment]
Cool. So we just need to fix the test, probably (or rather, see why it crashes). I'll keep this open until we figure out the crash.

**Comment by hobarrera** [comment]
For anyone wanting to look into this: I'd add a `tox` environment, that runs the entire test suite with `pyicu` as an extra requirement, so we're sure we never regress on this again.

**Comment by hobarrera** [comment]
This is an upstream issue, but I'm not sure if it's `freezegun` or `parsedatetime` that's failing here. Here's a minimal example reproducing the crash:

```
import parsedatetime
from freezegun import freeze_time


with freeze_time('2017-03-17 20:22:19'):
    parsedatetime.Calendar()
```

**Comment by hobarrera** [comment]
I've reported this upstream [here](https://github.com/spulec/freezegun/issues/207).
