### ISSUE TITLE
Proper logging

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#13]
This issue was moved from the issue tracker at GitLab.

---

Todoman currently has no way of emitting warnings, and a possibility to turn those warnings on and off. Warnings will probably be required for reporting invalid items (the current behavior is basically to ignore those, because logging handlers are not set up properly)

I'd like to rip out some code from vdirsyncer and https://github.com/mitsuhiko/click/pull/278, and make a third-party package on click-contrib to provide such things. I think I'll have to wait for Click 5.0 before implementing this though.

**Comment by untitaker** [comment]
click-log has existed for a long time and yesterday I even documented it

**Comment by hobarrera** [comment]
Yes, I think click-log was a bit green last time I looked at this issue (and was thinking of it when moving it here).
I'll look at the doc and give it a try (and any feedback) when I have some free time.

Thanks!

**Comment by untitaker** [comment]
API hasn't changed at all since a long time (mostly due to lacking feedback/userbase), and it's mostly just logging boilerplate code moved into a package.

**Comment by untitaker** [comment]
click-log has now existed for more than a year and hasn't changed at all. According to https://libraries.io/pypi/click-log there are 8 repositories dependent on it, though none of them have a significant popularity. On the other hand vdirsyncer isn't listed.

**Comment by hobarrera** [comment]
Yes, it looks quite popular: https://github.com/search?utf8=%E2%9C%93&q=%22import+click_log%22&type=Code&ref=searchresults

Yup, I'm okay with using it.

**Comment by untitaker** [comment]
It appears that GitHub's search is completely unusuable, this is also matched:

    import click
    log = ...

**Comment by hobarrera** [comment]
Yeah, lots of false positive, but if you scroll through them manually, you'll see there's lots of true positives too.
