### ISSUE TITLE
Use tabluate?

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#130]
Since formatting is starting to get more complex (#128 would add non-predictable column widths), maybe it makes sense to use something that *actually* renders tables, rather than just tabulating with a pre-defined amount of spaces.

* tabulate might be interesting: https://bitbucket.org/astanin/python-tabulate
* How does this affect performance? How much overhead does it add?
* Does it really make the code simpler?

**Comment by untitaker** [comment]
todoman currently expands  columns to the maximum length that is possibly needed, e.g. even when no task has a due date, the column is still created with the max width. This is more efficient to compute (vs linear scan through rows to find out the required width, which is what `tabulate` probably does)

**Comment by hobarrera** [comment]
Yup, current implementation is the most efficient, but:
* For very wide date+time formats, the gap may be very wide and make visually scaning rows hard.
* #128 will probably break the fixed-widthness.

**Comment by hobarrera** [comment]
Still, this issue is "let's evaluate if it's a good idea", I'm *not* saying that we should go straight for it.

**Comment by untitaker** [comment]
Sure, my comments were specifically regarding the second bullet point of the OP
