### ISSUE TITLE
Add list selector to TodoEditor

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#14]
This issue was moved from the issue tracker at GitLab.

---

Now that we support multiple vdirs, we need the editor to support picking one for new todos (and possibly existing ones too).

**Comment by AnubhaAgrawal** [comment]
Hi, I am new I would like to take up this issue.

In my opinion, I would have to make changes in the code [here](https://github.com/pimutils/todoman/blob/master/todoman/model.py#L456-L479).
Am I wrong?

**Comment by untitaker** [comment]
Hi @AnubhaAgrawal,

Sorry but no, this file has nothing to do with that. When running the interactive editor using `todo edit ...`, we want to show something that allows the user to move the task to a different task list. Please note this is a more difficult issue.

The entire editor interface is built up in [`TodoEditor.__init__`](https://github.com/pimutils/todoman/blob/master/todoman/ui.py#L27). The outermost widget is created on line 89, which chains all previous widgets (text fields, buttons) together.

1. We would have to create a new variable `self.current_list` which is initialized with `todo.list`.

2. [`urwid.RadioButton`](http://urwid.org/reference/widget.html#urwid.RadioButton) can do this, so you would have to create one radiobutton for each value in `self.lists`. If the radio button changes, `self.current_list` is changed to the new value

3. In `_save_inner`, `todo.list` is set to `self.current_list`

**Comment by hobarrera** [comment]
_Looks like @untitaker beat me and replied while I was still typing. Still, here goes._

Hi there! Thanks for your interest in todoman.

That's actually not right. Briefly:
* `cli.py` contains all the code involved in parsing commands/options and processing that. This is the starting point when running the app (and, admittedly, the more complex part, IMHO).
* `models.py` contains all the code involved in reading/writing/processing data (todos, lists, etc).
* `ui.py` has all the code for the *U*ser *I*nterface, including the `TodoEditor` class.

This issue is, _mostly_ in `ui.py`, and the above comments cover most of the relevant details.

**Comment by AnubhaAgrawal** [comment]
ok. I think firstly I'll try for some other issue

**Comment by AnubhaAgrawal** [comment]
sorry, for negative comment now I want to work on this issue.
can anyone tell that if  I want to print the values in self.lists then how to I get them?

**Comment by untitaker** [comment]
Hi, sorry for the slow response, if you want to find a different issue to work on that's fine of course.

I'm not sure if I understand your question. For this task you wouldn't have to print anything, but if you want to print the lists for debugging, print(self.lists) should be enough.

**Comment by AnubhaAgrawal** [comment]
No, as you(@untitaker) say that you would have to create one radiobutton for each value in .self.lists. but I don't find the values in self.lists.

**Comment by untitaker** [comment]
It appears `self.lists` is a generator, but `for list in self.lists` should still work. If you replace line `33` in `ui.py` with `self.lists = list(lists)`, you should see the values.

If you have time we can discuss this over [IRC](https://pimutils.org/contact/) because this allows for faster back-and-forth communication.
