### ISSUE TITLE
How to deal with invalid todos?

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#140]
If single properties are invalid, should we reject the entire file and print the path, or ignore the property to allow the user to fix the file with TodoEditor?

**Comment by hobarrera** [comment]
IMHO, it makes sense the most to print a warning when parsing it, and mark it `read-only` (since we can't save it without data-loss). Ideally, the warning should have enough information for the user to reach out to us and inform us of the issue.

**Comment by untitaker** [comment]
How would you make it read-only if you can't read it?

On 26 February 2017 14:05:29 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>IMHO, it makes sense the most to print a warning when parsing it, and
>mark it `read-only` (since we can't save it without data-loss).
>Ideally, the warning should have enough information for the user to
>reach out to us and inform us of the issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/issues/140#issuecomment-282554550

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Sorry, I meant to say that if a single properly is invalid, we should ignore the property, but mark the todo `read-only`.

**Comment by untitaker** [comment]
Ok. Should the warning show at every run of todoman?

On 26 February 2017 14:11:48 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Sorry, I meant to say that if a single properly is invalid, we should
>ignore the property, but mark the todo `read-only`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/issues/140#issuecomment-282554950

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
Ideally, no. I guess we can show it when caching the file. I'd prefer not to show it again if the file changed (eg: by vdirsyncer), but I'm not sure how.

**Comment by untitaker** [comment]
I'm unsure if this makes it too easy to miss the warnings (and therefore potential deadlines)

**Comment by hobarrera** [comment]
* We should show warnings once for unsupported fields (but process the rest of the todo).
* If we fail to load/cache a `todo`, avoid caching it, so the warning will trigger every run.
