### ISSUE TITLE
test_main.py assumes `python` exists

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#147]
`test_main.py` has this piece of code:
````
        pipe = Popen(
           ['python', '-m', 'todoman', '--version'], stdout=PIPE, env=env
        )
````
This will fail on some distros that do not provide a `python` executable. E.g., pkgsrc by default only provides versioned python binaries like `python3.6`.

**Comment by hobarrera** [comment]
You're right. We should determine which interpreter is being used at runtime be use that.

**Comment by untitaker** [comment]
Unsure if it's worth having this test, but `sys.executable` does what you want

**Comment by hobarrera** [comment]
Mostly:

* It makes sure we don't break `__main__` (unlikely, but might happen due to API change).
* It used to help me catch issues with my local test env (no longer applicable, but who knows).
* Higher test coverage (totally unimportant :P )
