### ISSUE TITLE
Sync issue with darwin calendar server

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#15]
This issue was moved from the issue tracker at GitLab.

---

I am trying creating a todo and then syncing it with darwin calendar server.
That fails with following error from darwin calendar server:

    2016-04-15 02:55:17+0300 [-] [caldav-1]  [-] [twistedcaldav.method.put_common#error] Invalid calendar data: Calendar data had unfixable problems:
    2016-04-15 02:55:17+0300 [-] [caldav-1]           [VTODO] Missing or too many required property: DTSTAMP

What I did:
1. I installed current version of todoman with pip.
1. Set up sync with darwin calendar server with vdirsyncer. Setup works (I can sync calendar/todo items, edit todos created from other sources, etc).
1. Tried to create new todo with following line: __todo new -l calendar "test todo"__
1. Todo is created locally and can be seen/modified
1. Sync fails with quoted error in server logs.

Resulting file (and file with same summary, but created from android "tasks" application, that syncs successfully are attached.
[fail.ics](/uploads/71ee030b4c82d2a875d43bd0b2e9953c/fail.ics)
[success.ics](/uploads/2208fb32e07c21c549f0aa2fdd75f586/success.ics)

The successful one does contain DTSTAMP field.

**Comment by hobarrera** [comment]
Indeed, it looks like `DTSTART` is a required field for `VTODO` entries, however, RFC5545 doesn't seem to specify what it should contain (and there's no coherent value I can think of either).

I'll try to look into this.

**Comment by untitaker** [comment]
DTSTAMP vs DTSTART.

**Comment by fhunter** [comment]
I found it here: http://www.ietf.org/rfc/rfc2445.txt and here: http://www.kanzaki.com/docs/ical/vtodo.html

Property Name: DTSTAMP
   Purpose: The property indicates the date/time that the instance of
   the iCalendar object was created.

**Comment by hobarrera** [comment]
Sorry, I mixed up `DTSTAMP` and `DTSTART`. It makes sense now.

**Comment by untitaker** [comment]
I wonder if we could make the case that icalendar should generate DTSTAMP implicitly. Otherwise it would create invalid iCalendars by default.

On 17 April 2016 14:24:14 CEST, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>Sorry, I mixed up `DTSTAMP` and `DTSTART`. It makes sense now.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/issues/15#issuecomment-211010155

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobarrera** [comment]
I've created `collective/icalendar#193`, to see if this can eventually be fixed upstream.
