### ISSUE TITLE
TodoEditor shows humanized datetimes in due field, may not be able to parse them back

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#158]
The textfield is prefilled with something like "Today 23:00", but it's unclear (or at least not guaranteed) that this is going to be parsed again correctly.

~~We need a flag for `format_due` to disable human datetimes and use that within TodoEditor.~~

**Comment by untitaker** [comment]
Turns out this has a common root cause together with #159, so the fix in the OP is inappropriate.

**Comment by hobarrera** [comment]
Actually, the solution proposed here is correct. **Not** relying on the formatter would mean that the produced `datetime` would not match the configured one.

**Comment by untitaker** [comment]
We do need to use the configured format, but just using the formatter from ctx.obj is flawed because of #159

**Comment by untitaker** [comment]
PR incoming
