### ISSUE TITLE
`todo --porcelain edit ...` crashes

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#159]
When providing todoman with the porcelain option, the TodoEditor crashes. This can be fixed together with https://github.com/pimutils/todoman/issues/158 by not relying on `ctx.obj["formatter"]` at all.

**Comment by hobarrera** [comment]
`PorcelainFormatter` should have the same API as `TodoFormatter`, so if it's lacking any methods, or methods have different signatures, it's a bug and I'm okay with changing it. :+1:
