### ISSUE TITLE
Support checklists

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#16]
This issue was moved from the issue tracker at GitLab.

[This](https://github.com/asalminen/todoman) fork may offer a fix for this.

---

It would be nice if todoman could support checklists. 
I know them from the android app OpenTasks. Here is (how i understand) they work:
- checklist items are appended to the Description as strings in the form '[ ] <text>' (unchecked) or '[x] <text>' (checked)
- only checklist item strings at the bottom of Description are 'real' checkbox items, if they're interlaeved with text, they're normal text, so it is some custom interpretation of Description I guess
- checklist item are displayed in a separate widget where you can toggle the state, delete them or add new ones

I hope this makes at least a little sense...
here is an example of todomans display for all my issues ;)

```
     Summary: todoman issues
 Description: [x] delete todos
              [ ] support checklists
              [x] interactive keybindings
    Location:
         Due:
   Completed: [ ]
      Urgent: [ ]

< Cancel >  < Save >
```

and here how it could look like:

```
     Summary: todoman issues
 Description: 
 Checklist:   [x] delete todos
              [ ] support checklists
              [x] interactive keybindings
              [ ] <new>
    Location:
         Due:
   Completed: [ ]
      Urgent: [ ]

< Cancel >  < Save >
```

where a checklist item is delete when no text remains and a new one is added when hitting <enter> in the textfield
I have no experience in urwid (or whatever you're using) so I am not sure this works at all 

P.S: Interesting how gitlab 'sees' those items and shows a status in the overview of the issue ;)

**Comment by asalminen** [comment]
Did fork for my open task needs.  Fork status is "works for me". Fork has some hard-coded view changes  which might not be welcome by others. And I do not use the interactive thingy thus no implementation for that at all ( normal free edit of tasks in description works ;).

If we get some more thumbs for this I could find time to implement this for interactive thingy ( have no idea how interactive works ;) and find way to have common (or some config file option) output style in command line with mainstream todoman.

**Comment by untitaker** [comment]
I might have a use for this as well. Current workaround for me is to use top-level tasks as vdirsyncer can't merge subtask changes anyway.

**Comment by asalminen** [comment]
vdirsyncer syncs subtasks just fine. Those are just description texts...

**Comment by untitaker** [comment]
If you edit two main tasks on both sides you get a conflict resolution. This is why I've been holding off using subtasks because neither DavDroid nor vdirsyncer merge changes to the description.

**Comment by asalminen** [comment]
Could be - I do recall having some conflicts early on. I presume my current work flow makes my desk always sync with phone before edit thus haven't seen conflicts for long time. One more works me, but is really quite hazard and going to fail in multi devise setup.

**Comment by hobarrera** [comment]
I'm inclined to close this because of it's non-standardness and intrinsic incompatibility with vdirsyncer. @untitaker?

**Comment by untitaker** [comment]
Go ahead

On 8 March 2017 16:19:45 CET, Hugo Osvaldo Barrera <notifications@github.com> wrote:
>I'm inclined to close this because of it's non-standardness and
>intrinsic incompatibility with vdirsyncer. @untitaker?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/issues/16#issuecomment-285069555

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
