### ISSUE TITLE
Todoman needs to deal with date vs datetime

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/todoman#165]
Cache stores stuff as timestamps, so when reading back, we always get a `datetime`. We need to find out how to deal with this (maybe a second column stating if it's a dt or not?).

**Comment by untitaker** [comment]
Right now it doesn't really need to since we intentionally conflate dates and datetimes much earlier.

**Comment by hobarrera** [comment]
Yeah, you're right, the whole stack need to deal with this.

**Comment by hobarrera** [comment]
Another option is to have separate columns for `due_date` and `due_time` (everything stored in UTC). This sounds quite a bit simpler.

**Comment by untitaker** [comment]
Not sure if this is simpler actually, since it makes sorting and filtering by due date more complex.

**Comment by hobarrera** [comment]
Yeah, it's not actually _"simpler"_, it's just the _"the only approach I can think of"_.  
Do you actually know how khal deals with this?

**Comment by untitaker** [comment]
khal appears to use a `dtype` flag with two values, stored as `INT`.

**Comment by hobarrera** [comment]
Right, that's actually simpler (and keeps comparisons simple). We just need to deserialize accordingly. :+1:
