### ISSUE TITLE
Done seems to delete repeating reminders

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#17]
This issue was moved from the issue tracker at GitLab.

---

When I use todoman to mark repeating reminders "done", the repeating reminders disappear entirely, and are not rescheduled.

I am using todoman version 1.5.2.

**Comment by hobarrera** [comment]
This was also reported on a different issue by @languitar

**Comment by rajalakshmi-v15** [comment]
hi,
I want to help fix this issue. I am new to this project and am interested in working on this particular issue. Please guide me.

**Comment by untitaker** [comment]
I'm not entirely sure what is needed for this issue, but I consider it to be very long-term (and very hard). Not sure if having the rgsoc label on it is a good idea.

**Comment by rajalakshmi-v15** [comment]
We hoped to work on this issue for RGSoc. Could you suggest any other issue which might be suitable to be worked on during the summer?

**Comment by untitaker** [comment]
We currently have more participants than issues, though I think #62 isn't taken. But I'd wait for @hobarrera's response.

**Comment by hobarrera** [comment]
This specific issue is a bit long, so it might be suitable to work during the summer (as a long-term one), *however* I do suggest that you pick one labelled `lv:easy` first to get acquainted with todoman.

Also, @untitaker is right, we also have to define a few thing before we can tackle this one.

**Comment by hobarrera** [comment]
So, currently, for this task, we need to:

* Design how we'll model recurring tasks.
* Investigate how we mark done instances (I'd have to re-read the RFC, but, so far, I didnt' find anything useful) I might opt for using some `X-Last-Done`, which keeps the datetime of the last instance marked as done.

I believe that iOS deals with this by using alarms, which we also don't support, but should

**Comment by hobarrera** [comment]
So what iOS does is pretty simple (I tried this with a monthly recurring todo I actually needed). It simply creates a normal recurring event, and when I mark it done here's what happens:

* A copy of the vtodo is made, but sets the copy's DTSTART and DUE to the next instance's date.
* It remove the RRULE from the original copy.
* The copy gets a different UID.
* It sets the original copy's COMPLETED and PERCENT-COMPLETE field, as well as updating the STATUS field.
* The ALARM for the new copy also has it's date pushed to the next instance, but the AKNOWLEDGED attribute is set for it (IMHO, the old copy should have this set).

What I don't understand is how iOS recognized both as the same recurring todo. It probably doesn't, since clicking _show completed_ shows me the done copy, while I can see the incomplete copy above.

I kinda like this behaviour. It has no non-standard things, imitating it makes us iOS-compatible, and I don't have any better ideas (this last point is the most important). The spec kinda leaves a grey area on this.
