### ISSUE TITLE
Editing or adding new items always moves them to midnight

### ISSUE THREAD

**Issue by lenalebt** [pimutils/todoman#172]
Whenever I add a new todo or edit another one, the due time gets moved to midnight (the date itself is fine), making my phone ring in the night to remind me about `$important_stuff`.

While it would be great to be able to edit the due time as well, a quickfix like moving it to some fixed time during the day instead of midnight would already help a lot.

Tested with todoman 2.1.0 (latest updated with pip today).

**Comment by untitaker** [comment]
For todoman to support times, you have to set `date_format` to something like this:

    date_format = %Y-%m-%d %H:%M

This was never intended to work that way (latest todoman just doesn't support times at all). In master you can do this:

    date_format = %Y-%m-%d
    time_format = %H:%M

**Comment by hobarrera** [comment]
If this is not the issue, did your todos originally have a time, or just a date?

**Comment by lenalebt** [comment]
Hi both,
all my tasks have times on their due dates set, and they are very different (e.g. "call the dentist for an appointment" usually is at a time where the dentist actually can be called, where "buy milk before coming home" usually is at another time.

I think it already solves my issue this way, setting `date_format = %Y-%m-%d %H:%M` was all I needed. Thanks for the software, and the quick response - keep the good work going :).

**Comment by untitaker** [comment]
Great, let's close this then.
