### ISSUE TITLE
Add tests for all errors raised in cli.py

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#175]
Some of these errors are off, and are usually not covered by tests. Here's one:

If `default_list = nonexistant`:

```
$ todo new dafsd
Usage: todo new [OPTIONS] [SUMMARY]...

Error: Invalid value for "--list" / "-l": nonexistant. Available lists are: holidays, study, personal, work
```

In this case:
* Config was wrong
* There was no `-l`

**Comment by mansimarkaur** [comment]
I'd like to work on this issue.

**Comment by hobarrera** [comment]
Hi, thanks!

So, for this issue, we need to look at all places that raise an error in `cli.py`, and make sure that some test triggers that error (like [this one](https://github.com/pimutils/todoman/blob/master/tests/test_cli.py#L29-L34)). This is because we've already broken these code paths before without realizing it and I'd like to avoid this happening again.

It's possible that some tests reveal that some cases are broken (the one mentioned in this issue definitely is), so we also need to fix those. The one mentioned above is **not** an easy one to start with.

If you want to quickly check which parts are not covered by tests, you can use `coverage`:

```bash
py.test --cov
coverage report -m
```

It's also visible [here](https://codecov.io/gh/pimutils/todoman/tree/master/todoman) (this won't reflect local changes, of course).

Oh, we might also want to include `configuration.py` for this one.

**Comment by hobarrera** [comment]
We gradually reached a point where this is covered.
