### ISSUE TITLE
Filter by timerange

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#18]
This issue was moved from the issue tracker at GitLab.

---

`todo list` should be able to filter a timerange, i.e.:

```
todo list --start="before 2015-10-12"
todo list --due="before 2015-10-16"
```

like thunderbird lightning, pre-configured timerange filters would be handy:

```
todo list --timerange=current
todo list --timerange=today
todo list --timerange=7days
todo list --timerange=overdue
todo list --timerange=not_started
```

i don't know if it's better to implement a special timerange filter, or a more generic filter that can be preconfigured, which could filter by other things as well like lighning:

```
todo list filter=completed
todo list filter=incomplete
```

customizing those filters would be supreme :D

**Comment by Swati4star** [comment]
Hi @hobarrera I would like to work on this issue.
Any suggestions?

**Comment by untitaker** [comment]
My two cents: Implement `--start` and `--due` and see where this goes. Specialized filters can more easily be implemented as shell aliases, wrapper scripts etc, though we might want to add direct support on this.

**Comment by hobarrera** [comment]
Do keep in mind that we already have a `--due` filter defined:

    --due INTEGER             Only show tasks due in DUE hours

**Comment by Swati4star** [comment]
@hobarrera @untitaker I wanted to ask what exactly do you want in this
```

todo list --timerange=current
todo list --timerange=today
todo list --timerange=7days
todo list --timerange=overdue
todo list --timerange=not_started
```

It is kind of not clear. What exactly does timerange specify?

**Comment by hobarrera** [comment]
I think we've covered this with `--due`. I'll revise this in future, but I think this issue is pretty much covered.

**Comment by Swati4star** [comment]
Should we close this issue then?
All the mentioned features are covered now.

**Comment by untitaker** [comment]
Yup
