### ISSUE TITLE
option for todos which shall appear daily

### ISSUE THREAD

**Issue by RJ722** [pimutils/todoman#220]
There should be an option in todos such that they appear everyday at 00:00, so that we can schedule todoman for our routine tasks.
For eg, I have made it my personal goal to review a PR everyday, and so I have to add a new todo everyday in the morning, it's a bit annoying :crying_cat_face:!

**Comment by hobarrera** [comment]
What you want is basically recurring/repeating events. See #17. This is planned, but no-one is working on it yet.

If you don't want it to appear until midnight, you'd just have to set the `start` to midnight, and run `todo list --today` (which lists only todos that can be started today --- that is: not in a future day).

**Comment by hobarrera** [comment]
Closing in favour of #17.
