### ISSUE TITLE
todo edit <change id> after editing

### ISSUE THREAD

**Issue by AnubhaAgrawal** [pimutils/todoman#226]
I think we must have to include the feature that after doing ```todo edit``` the id of a task does not change because if we want that there is some tasks in sequence and want to edit in the middle task then it creates problem.
or we include something like, ```do you want to change id or not ??``` after todo edit.

**Comment by hobarrera** [comment]
I though we already had an issue open for this, but yeah, that's a bug. It shouldn't change, even. We shouldn't even ask, it should always stay the same.

**Comment by untitaker** [comment]
That is the closed https://github.com/pimutils/todoman/issues/85

**Comment by AnubhaAgrawal** [comment]
I am totally confused because I think this issue is already solved. Now by doing  ```todo edit ```  id of task does not change.

```(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo new --list Anu

16  [ ]    2017-04-01 08:42:18 PM  Hello @Anu

Description  Checking Editing
Location     Boston
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo show 16
16  [ ]    2017-04-01 08:42:18 PM  Hello @Anu

Description  Checking Editing
Location     Boston
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo edit 16
16  [ ]    2017-04-01 08:42:18 PM  Hello everyone @Anu

Description  Checking Editing1
Location     Boston1
(venv) anubha@anubha-Inspiron-3542:~/Desktop/todoman$ todo show 16
16  [ ]    2017-04-01 08:42:18 PM  Hello everyone @Anu

Description  Checking Editing1
Location     Boston1
```

**Comment by untitaker** [comment]
Hmm. I suppose we can close this then. Did you do `git pull` or update todoman?

**Comment by AnubhaAgrawal** [comment]
yes I do git pull and then when I do ``` todo edit``` it's id does not change

**Comment by untitaker** [comment]
Ok then I think this is already fixed.
