### ISSUE TITLE
uncommon pytest arguments

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#233]
When trying to run the tests with `py-test-3.0.7` installed, I see
````
usage: setup.py [options] [file_or_dir] [file_or_dir] [...]
setup.py: error: unrecognized arguments: --cov=todoman --cov-report=term-missing
  inifile: .../todoman-3.0.1/setup.cfg
  rootdir: .../todoman-3.0.1
*** Error code 2
````
Removing the line from `setup.cfg` makes the tests work for me.

**Comment by hobarrera** [comment]
You need to install `coversge`. Or rather, you need to have `requirements-dev` installed for this sort of thing.

**Comment by 0-wiz-0** [comment]
Thanks, I installed all the requirements mentioned there and the tests ran through.
