### ISSUE TITLE
Choose priority when adding a new task from cli

### ISSUE THREAD

**Issue by varac** [pimutils/todoman#239]
Describtion sais it all, sth like:

```
    todo new --priority high 'Choose priority when adding a new task'
```

**Comment by AnubhaAgrawal** [comment]
I want to solve this issue.

**Comment by untitaker** [comment]
Cool!

This option is very similar to https://github.com/pimutils/todoman/blob/e7cfe9bdf166e39c94b0c29a7e201c13ba584268/todoman/cli.py#L477, like you did for `--location` in #163 you should add an option like this to `_todo_property_options`.

**Comment by AnubhaAgrawal** [comment]
I got an error in test_cli.py, that is test cases are failed. but I don't understand the problem so I PR my changes.
