### ISSUE TITLE
[Enhancement] Add search subcommand

### ISSUE THREAD

**Issue by samdmarshall** [pimutils/todoman#244]
Add a subcommand to allow for searching for tasks based on name and contents to filter and locate tasks in a large list.

**Comment by untitaker** [comment]
`list`'s `--grep` option offers fulltext search, among other search options.

**Comment by samdmarshall** [comment]
Ah-ha, so it does, that was a little less obvious to check that subcommand's help text that it could have been. I don't have any good suggestions for making it better at the moment so i'll go ahead and close this. Thanks!
