### ISSUE TITLE
sphinx_autorun: repo not available anywhere

### ISSUE THREAD

**Issue by legrostdg** [pimutils/todoman#245]
sphinx_autorun is required to build todoman's doc, but no repo seems to be available. It is needed if we want to have a Debian package of it.

**Comment by hobarrera** [comment]
Repository: https://gitlab.com/hobarrera/sphinx-autorun
PyPI/packages: https://pypi.python.org/pypi/sphinx-autorun/1.0.0

**Comment by legrostdg** [comment]
> Repository: https://gitlab.com/hobarrera/sphinx-autorun

I should have mentioned that I already seen this, but that it 404's

**Comment by hobarrera** [comment]
Silly, silly me, the repo was private (so the link worked for me). Fixed now.

**Comment by legrostdg** [comment]
I can now open https://gitlab.com/hobarrera/sphinx-autorun in a browser, but I can't clone the repo:

    $ git clone https://gitlab.com/hobarrera/sphinx-autorun.git
    Cloning into 'sphinx-autorun'...
    Username for 'https://gitlab.com':

**Comment by hobarrera** [comment]
Use git via ssh. I've never used git over https, so I've no idea how to configure that.

**Comment by legrostdg** [comment]
? I just want to copy the repo without a gitlab account.

    $ git clone http://gitlab.com/hobarrera/sphinx-autorun.git
    Cloning into 'sphinx-autorun'...
    Username for 'https://gitlab.com': ^C

**Comment by hobarrera** [comment]
Doesn't this work?

    git clone git@gitlab.com:hobarrera/sphinx-autorun.git

Again, I've never used git+https, so I can't help there at all.

**Comment by legrostdg** [comment]
$ git clone git@gitlab.com:hobarrera/sphinx-autorun.git
    Cloning into 'sphinx-autorun'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

**Comment by legrostdg** [comment]
If you don't know how to publish a repo to the public on gitlab, can!t you just clone it to github?

**Comment by hobarrera** [comment]
Dah, yeah, looks like switching the repo from private to public is bugged and isn't giving you access.

Here's a mirror: https://github.com/hobarrera/sphinx-autorun

**Comment by legrostdg** [comment]
Great, thanks!

**Comment by hobarrera** [comment]
> If you don't know how to publish a repo to the public on gitlab, can!t you just clone it to github?

Oh, I *did* make it public, it seems there's a bug and making it public made the page public, but not the repo (LAME!).
