### ISSUE TITLE
Allow sorting by multiple fields

### ISSUE THREAD

**Issue by varac** [pimutils/todoman#250]
Currently, todoman can sort by one field. It would be great to sort either by multiple fields. I.e. first sort by priority and for each priority, sort by due date.
This would be really useful.

**Comment by varac** [comment]
i.e.:

```
todo list --sort priority --no-reverse
```

sorts nicely by priority, but the due dates in each category are randomly sorted.

sth like this would be great:

```
todo list --sort priority,due --no-reverse
```

**Comment by varac** [comment]
Omg, this already works :) Awesome!

**Comment by hobarrera** [comment]
🎉
