### ISSUE TITLE
Release v1.6.1

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#26]
v1.6.0 was broken and pulled back. Master has been fixed, and v1.6.1 needs to be published.

Publishing v1.6.1 failed due to a pypi error, reported [here](https://bitbucket.org/pypa/pypi/issues/442/500-server-error-trying-to-register).

**Comment by untitaker** [comment]
Had similar issues for other projects, just bump the version again...

**Comment by hobarrera** [comment]
Only partially worked; pypi got fixed, but the [tarball](https://pypi.python.org/packages/source/t/todoman/todoman-1.6.2.tar.gz) isn't available. :(

**Comment by hobarrera** [comment]
This was fixed some time ago by using [pypi.io](https://pypi.io/packages/source/t/todoman/todoman-1.6.3.tar.gz) tarballs.
