### ISSUE TITLE
todoman-3.2.2: not uploaded to pypi

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#278]
Please release todoman-3.2.2. on pypi. Thank you.

**Comment by hobarrera** [comment]
I pushed it four days ago, but it hasn't shown up yet. PyPI has been more and more unreliable the last months, and it's not the first time a package isn't showing up a few days later.

You can use the packages [here](https://github.com/pimutils/todoman/releases/tag/v3.2.2) in the meantime.

**Comment by hobarrera** [comment]
I've made some changes to v3.2.3 due to some PyPI-related changes.

Looks like this time it's not taking some time; it's simply absent from PyPI. I've no idea what's going on there.

**Comment by WhyNotHugo** [comment]
I've changed how packages are uploaded since this, and recent packages have been appearing without issues. Deploys are now also logged better to track if something goes wrong on our end.
