### ISSUE TITLE
Filter out colors if piped to other command

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#29]
Currently, `todo list | cat` outputs colors. I think it shouldn't, and also should get a `--color` option (see khal).

Opinions?

**Comment by hobarrera** [comment]
I'd have a `colour` attribute with `always|auto|never`. `auto` strips if and only if the output is not a terminal.

I'd also have a configurable default (since in my case I'd want `always` -- because I like coloured `less`).
