### ISSUE TITLE
Valid fields for `--sort` are undocumented

### ISSUE THREAD

**Issue by WhyNotHugo** [pimutils/todoman#293]
We don't list the options valid for `--sort` anywhere, and the only way to find out what they are is inspecting the code.

**Comment by rimshaakhan** [comment]
Hey! I would like to work on this issue.
The relevant fields for --sort are :- 
DATE_TIME FIELDs
INT_FIELDs
LIST_FIELDS
RRULE_FIELDS
STRING_FIELDS

Should I add it along the help text of --sort or add it in some document file?

**Comment by untitaker** [comment]
Hello Rimsha,

I think it would make sense to have the most important fields one would
typically like to sort by in the helptext (e.g. start, due, priority,
created_at), and put the rest in the documentation (probably into
https://github.com/pimutils/todoman/blob/master/docs/source/usage.rst) and link
that page from the help text.

**Comment by rimshaakhan** [comment]
Hey @untitaker @WhyNotHugo ! 
For now I have added the important fields in the helptext. To add the remaining fields in todoman/docs/source/usage.rst should I add a separate subheading?

**Comment by RJ722** [comment]
Which ones have you marked important?

**Comment by RJ722** [comment]
IMHO as a user, the most commonly used sorting parameters may be:
* `priority`
* `start`
* `due`
* `last_modified`
* `percent_complete`

**Comment by untitaker** [comment]
@rimshaakhan yes I think that makes sense. Thanks!

**Comment by untitaker** [comment]
@rimshaakhan yes that makes sense IMO, but I think it would be better if the docs would contain all fields instead of just the remaining ones. Thanks!

@RJ722 I agree

**Comment by rimshaakhan** [comment]
@WhyNotHugo @untitaker I have sent a PR. Please review.
