### ISSUE TITLE
sorting by location doesn't work

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#295]

**Comment by untitaker** [comment]
@RJ722 Actually I can't reproduce this, sorry. Location sorting works fine for me...

Regarding your example with UID, the IDs you see in the output of todo are not UIDs. Try `todo list --sort id`

**Comment by RJ722** [comment]
> Location sorting works fine for me...

So sorry, my fault!

> Regarding your example with UID, the IDs you see in the output of todo are not UIDs. Try todo list --sort id

Oh! This works fine, Thanks! :-)

I think we can close this issue.

**Comment by untitaker** [comment]
Ok cool
