### ISSUE TITLE
Add ability to hide task list name (f.e. when using only one task list)

### ISSUE THREAD

**Issue by stevenroose** [pimutils/todoman#301]

**Comment by WhyNotHugo** [comment]
Yeah, I think it kinda makes sense to hide the list name if all `todos` belong to a single list (or if filtering by a single list).

I'll keep this I mind, patches welcome.

**Comment by Phenitei** [comment]
I opened PR with a fix that hides the list when the database contains only one list, or if the list command is called with exactly one list as a filter.
