### ISSUE TITLE
Project's future

### ISSUE THREAD

**Issue by aleprovencio** [pimutils/todoman#306]
Hello guys, I've not seen much activity on this cool project lately, especially from @whynothugo, is there anything happening or is it just lack of available time?

**Comment by WhyNotHugo** [comment]
Personally, I'm a bit short on time, but I also feel the project is pretty mature and works "pretty well enough" for my everyday usage.

That doesn't mean I don't want to further improve it -- it just means that what little free time I have, I don't have a huge need to invest it here.

That said, bugs WILL get squashed, and I'm still happy to look at PRs and interesante proposals.

**Comment by aleprovencio** [comment]
That's just fine @whynothugo, and I'm very thankful for your work up to now.  I wish I could help you on todoman but although motivation is high, free time has also been an issue lately. Anyways, I'm glad you're not quiting on it ! :)
