### ISSUE TITLE
Preemptively validate configuration

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#31]
While working on #30, I saw that todoman just passes the raw configparser through the CLI. I think it would be better if there was a dedicated Config type that has all valid params as properties (which raise if somebody tries to set an invalid value).

khal uses ConfigObj for this.

**Comment by hobarrera** [comment]
We *might* want to close this if we merge #59, though that would have to be a mayor release, since it's backwards-incompatible.

**Comment by untitaker** [comment]
agreed
