### ISSUE TITLE
todo repl exits after any successful command

### ISSUE THREAD

**Issue by privong** [pimutils/todoman#327]
In at least the most recent version, `todo repl` exits every time a command successfully executes, with an exit code of `0`. If a command is not successful, it prints the help message but does not exit. Sample flow below:

```
$ todo --version
todoman, version 3.4.1

$ todo repl
> new -l personal "file bug report"
655  [ ]    in 2 days  file bug report @personal

$ todo repl
> list personal
655  [ ]      in a day              file bug report @personal

$ todo repl
> delete
Usage: todo  delete [OPTIONS] IDS...
Try "todo  delete --help" for help.

Error: Missing argument "IDS...".
> delete 655
655  [ ]    in a day  file bug report @personal
Do you want to delete those tasks? [y/N]: y
Deleting "file bug report"

$ echo $?
0
```
(spacing added to make separate invocations more clear)

I am running Arch Linux. The `python-click-repl` package version is 0.1.5-1, `python-click` is version 7.0-1, and `python-prompt_toolkit` is 1.0.15-2.

It's unclear to me if this is related to #326, since my installation seems to successfully run at least one command.

**Comment by WhyNotHugo** [comment]
This is a bug in click-repl. See https://github.com/click-contrib/click-repl/pull/51

Not much that we can do on our end in the meantime.

**Comment by untitaker** [comment]
I am not obv much involved into this anymore, tell me if you need something merged or want release access

**Comment by theazureshadow** [comment]
@untitaker: My PR #51 should fix this issue, if you want to merge and cut a release.

**Comment by untitaker** [comment]
Thanks and sorry for the delay

**Comment by privong** [comment]
Thanks, all. Arch has updated the click-repl package and I can verify that this issue is solved for me. Closing the ticket.

**Comment by WhyNotHugo** [comment]
Thanks for picking this up and closing it guys! :)
