### ISSUE TITLE
sqlite3.InterfaceError: Error binding parameter 13 - probably unsupported type

### ISSUE THREAD

**Issue by legrostdg** [pimutils/todoman#333]
`todoman` does not build anymore on Debian unstable: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912098

**Comment by legrostdg** [comment]
... probably because of a dependency update...

**Comment by dvzrv** [comment]
[Same problem on Arch Linux](https://bugs.archlinux.org/task/60795).

**Comment by WhyNotHugo** [comment]
This was fixed by 3e191111b72df9ec91a773befefa291799374422.

I'll try and release a new version tomorrow.

**Comment by WhyNotHugo** [comment]
Release v3.5.0. Should show up on PyPI and releases in a few minutes.
