### ISSUE TITLE
UI: Save and delete are too close to each other

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#34]
I don't really see the need for having this option in the editor too, since the CLI has this option already.

**Comment by hobarrera** [comment]
I've been a bit scared of accidentally hitting delete too - I'm pretty sure we need a confirmation button, or the just delete this.

**Comment by untitaker** [comment]
Do you think it would make sense to add a confirmation to `todo delete` as
well?

**Comment by wilbowma** [comment]
On Thu, May 26, 2016 at 10:15:22AM -0700, Markus Unterwaditzer wrote:
> Do you think it would make sense to add a confirmation to `todo delete` as
> well?
I for one would appreciate that.

**Comment by untitaker** [comment]
There is now a confirmation option on `todo delete`. Can't we just remove this button?

**Comment by untitaker** [comment]
Also `cancel` isn't needed either, `^C` works.

**Comment by hobarrera** [comment]
> There is now a confirmation option on todo delete. Can't we just remove this button?

Yeah, it's a bit scary IMHO, and `todo delete` is probably enough. Deletion is not meant to be a common operation anyway.

> Also cancel isn't needed either, ^C works.

I'm not sure if <kbd>ctrl</kbd>+<kbd>c</kbd> is obvious or not. Apps where it works usually still tend to have an exit/cancel button.

**Comment by untitaker** [comment]
Perhaps a text under the buttons: "Hit Ctrl-C to cancel"?

**Comment by hobarrera** [comment]
That sounds okay. It could also be in a status bar, though we don't have one yet.

**Comment by untitaker** [comment]
#46 is ready for review
