### ISSUE TITLE
Start date is missing in outputs

### ISSUE THREAD

**Issue by GSI** [pimutils/todoman#344]
Start date should at least be included in `todo --porcelain`.

Also, maybe it would be a good idea to set it to the task creation date by default (?)

**Comment by WhyNotHugo** [comment]
> Start date should at least be included in `todo --porcelain`.

Definitely.
 
> Also, maybe it would be a good idea to set it to the task creation date by default (?)

It might be a configuration option, but by default, I wouldn't include one, since it's not what most users would expect.

**Comment by skowalak** [comment]
Hello @WhyNotHugo,
I would like to implement this feature (include start date in porcelain formatter). Is it okay if I create a PR for it? Is there anything I need to read before contributing?

Thank you!

**Comment by WhyNotHugo** [comment]
Go ahead. I think that looking at other date fields is a good reference.

**Comment by skowalak** [comment]
I added a PR, thanks for your help!
