### ISSUE TITLE
[question/request for documentation] document how to configure timezone

### ISSUE THREAD

**Issue by Konfekt** [pimutils/todoman#345]
Whereas for example `khal` has a setting https://github.com/pimutils/khal/blob/master/doc/source/usage.rst#new to define the timezone, there does not seem to be a such in `todoman`. Is the environment variable `$TZ` used instead? It would be good to know.

**Comment by Konfekt** [comment]
At least https://todoman.readthedocs.io/en/stable/configure.html or grepping through the repo did not reveal such a setting.

**Comment by WhyNotHugo** [comment]
todoman will use the system-wide configure timezone. If this doesn't work for you, you _may_ override the timezone by specifying the `TZ` environment variable.
