### ISSUE TITLE
Print output with plain text--i.e. not color formatted

### ISSUE THREAD

**Issue by ign1s-fatuus** [pimutils/todoman#349]
Just a suggestion but it might be useful to print the output without color-formatted text. While I am actually in support of more color support throughout the project as a whole, it could be useful to have a --no-color option for those wanting to print the output for the use of commands not yet supporting color formatting. 

Case in point: I currently set up keybindings for each of my calendar-linked task list which prints the output to dunst via notify send. Dunst, as far as I can tell, cannot intemperate the color formatting being output by todo. Before doing this I have to strip away all of the color formatting with something along the lines of `notify-send "$(echo -e "\t\t\tComputer\n"; todo list computer --no-reverse --status ANY | tr -dc '[:print:]\n\r\t' | sed 's/\[[0-9][0-9];.*\[0m//g;s/\[[0-9][0-9]m//g;s/\[0m//g')"`. Calling this command from xmonad via haskell gets even more ugly. 

In sum, while not a deal breaker, I could certainly see some utility in having the option to output text without color formatting

**Comment by WhyNotHugo** [comment]
I think `todo --colour=never` should do the trick.

For scripting. `todo --porcelain` piped with `jq` might also be worth looking at.

**Comment by ign1s-fatuus** [comment]
Thanks, I'll have to take a look at that. I could have sworn that I had gone over the docs a couple of time looking for a no color option; I must have missed it. Again, though, you've been a big help!
