### ISSUE TITLE
iOS todos not found

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#35]
I created some todos on iOS and synced them with vdirsyncer.
I configured todoman to look in the appropriate directory, and when I trace the process, I see that it stats the .ics files.
However, `todo list` does not show any of them.
`.cache/todoman/ids` just consists of one line: `[]`
Let me know if you need one of the todos as example.

**Comment by hobarrera** [comment]
Yes, please, an example todo would be great to see what's going on. Can you please also include your settings? Thanks!

**Comment by 0-wiz-0** [comment]
Sure. Here's the config file:
````
[main]
path = ~/.calendars/97D2B267-527A-445D-9F4C-5A0152707F79/*
````
and here's one example, `3F5A66F2-F3AF-4E1E-AEE9-A9B15BA1EDD3.ics` from that directory:
````
BEGIN:VCALENDAR
CALSCALE:GREGORIAN
PRODID:-//Apple Inc.//iOS 9.3.3//EN
VERSION:2.0
BEGIN:VTODO
CREATED:20160731T221712Z
DTSTAMP:20160731T221717Z
LAST-MODIFIED:20160731T221714Z
SEQUENCE:0
STATUS:NEEDS-ACTION
SUMMARY:Essen
UID:3F5A66F2-F3AF-4E1E-AEE9-A9B15BA1EDD3
X-APPLE-SORT-ORDER:491696232
END:VTODO
END:VCALENDAR
````

**Comment by hobarrera** [comment]
`~/.calendars/97D2B267-527A-445D-9F4C-5A0152707F79/*`

The `*` here is expanded to match anything inside that directory, and those matches are considered directories with `ics` files.

I think that what you want is:

`~/.calendars/97D2B267-527A-445D-9F4C-5A0152707F79/`

**Comment by 0-wiz-0** [comment]
Thank you, that is indeed the fix.
Please improve this part of the docs:
````
path: The path to where your todos are located. It can also be a glob expresion if you wish to include mutiple directories.
````
expresion -> expression
mutiple -> multiple

Perhaps:
````
path: A pattern matching the directory or directories where your todos are located (not the todo files themselves). It can also be a glob expression if you wish to include multiple directories.
`````

**Comment by hobarrera** [comment]
Indeed, I'll leave this open until I've improved the docs, thanks for
the feedback


On Tue, Aug 2, 2016, at 17:06, Thomas Klausner wrote:
> Thank you, that is indeed the fix.
>  Please improve this part of the docs:


> path: The path to where your todos are located. It can also be a glob
> expresion if you wish to include mutiple directories.
>
> expresion -> expression
>  mutiple -> multiple
> Perhaps:


> path: A pattern matching the directory or directories where your todos
> are located (not the todo files themselves). It can also be a glob
> expression if you wish to include multiple directories.
>
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>

--
Hugo Osvaldo Barrera


Links:

  1. https://github.com/pimutils/todoman/issues/35#issuecomment-237026920

**Comment by untitaker** [comment]
Opened a PR at #37.

**Comment by untitaker** [comment]
Perhaps we can make todoman detect such situations and show a better error message.

**Comment by hobarrera** [comment]
> Perhaps we can make todoman detect such situations and show a better error message.

Agreed
