### ISSUE TITLE
Allow customizing the time the day starts with "today" and "tomorrow"

### ISSUE THREAD

**Issue by dmp1ce** [pimutils/todoman#353]
When using a command such as `todo new --start today "My Task"` the task starts at 9am. To my knowledge this is not customizable with todoman.

Can the start time of the day be customized with todoman?

Or maybe I should just start sleeping in? 🙂

**Comment by WhyNotHugo** [comment]
Sounds pretty simple. I'll look at it when I get a bit of free time.

**Comment by dmp1ce** [comment]
Thanks. I wasn't sure were to look for the humanize code. I figured 9am is hard coded somewhere.

**Comment by WhyNotHugo** [comment]
Darn, I know this was kinda hardcoded, but I can't quite figure out where that is.

@untitaker Do you have a clearer idea of this maybe?

**Comment by untitaker** [comment]
"9am" is a default in the library we use to parse this (afaik it was https://github.com/bear/parsedatetime).

You can write "8am" or "today 8am" to change it. If there's no indication of date, it's today. If there's no indication of time, it's 9am.

Those are the rules I remember, but I am not sure if they can be changed. I remember their extended API being quite contrived.

**Comment by dmp1ce** [comment]
Thank you! For me there is no need to create a new default in config. I'll just use `today 7am`. Thanks!

**Comment by WhyNotHugo** [comment]
I'll go ahead and close this then, unless there's further demand for this feature.
