### ISSUE TITLE
Suggestion Namespace

### ISSUE THREAD

**Issue by 927589452** [pimutils/todoman#354]
A very handy feature would be to define namespaces like vdirsyncer does
like

[work]
path= .calendars/work

[personal]
path= .calendars/personal

and returning the calendars with a prefix to help with standard todolist/calendars

work_personal
personal_personal

**Comment by 927589452** [comment]
Though a paragraph in FAQ

like

**Problem:** Multiple Accounts using the same name for calendars
**Solution:** Use the [displayname] feature; a file named "displayname" 
                  containing a string will be used as list and human readable name
                  for todoman

**Comment by WhyNotHugo** [comment]
Looks like this is kinda address by using `displayname`, though the documentation around it could be improved. Let's continue discussion in  #355.
