### ISSUE TITLE
Please make proper 3.7.0 release

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#366]
There is a 3.7.0 tag but it doesn't include a .tar.gz file, and the autogenerated github tar.gz is not usable by setuptools_scm. Please upload a proper .tar.gz and/or make a pypi release. Thank you!

**Comment by WhyNotHugo** [comment]
Re-pushed the tag. Not sure why CI didn't trigger the first time. :thinking: 

It ran now, tarball, wheel and pypi showed immediately.
