### ISSUE TITLE
failed to read entry x-relative

### ISSUE THREAD

**Issue by Konfekt** [pimutils/todoman#386]
On reading an ICS file with a key `X-RELATIVE` in the field `RRULE:`, the error occurs:

```python
Failed to read entry /home/konfekt/.local/share/vdirsyncer/todo/all/task.ics.
Traceback (most recent call last):
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 1007, in update_cache
    self.cache.add_vtodo(component, entry_path)
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 651, in add_vtodo
    self._serialize_rrule(todo, 'rrule'),
  File "/home/konfekt/.local/lib/python3.6/site-packages/todoman/model.py", line 584, in _serialize_rrule
    return rrule.to_ical().decode()
  File "/home/konfekt/.local/lib/python3.6/site-packages/icalendar/prop.py", line 676, in to_ical
    typ = self.types[key]
  File "/home/konfekt/.local/lib/python3.6/site-packages/icalendar/caselessdict.py", line 42, in __getitem__
    return super(CaselessDict, self).__getitem__(key.upper())
KeyError: 'X-RELATIVE'
```

This key is used for a relative due date in repetitive tasks.

**Comment by WhyNotHugo** [comment]
I don't think I quite follow. Can you provide a sample of an ICS file that fails? (feel free to change the description and anything sensitive in it).

**Comment by Konfekt** [comment]
For example,  the following file would produce this error:

```
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VTODO
DUE;TZID=Europe/Berlin:20200516T100000
SUMMARY:Test
DESCRIPTION:Test
CLASS:PRIVATE
LAST-MODIFIED:20200419T131234Z
RRULE:FREQ=MONTHLY;INTERVAL=3;X-RELATIVE=1
STATUS:NEEDS-ACTION
UID:4283265
END:VTODO
END:VCALENDAR
```

**Comment by WhyNotHugo** [comment]
Yeah, `X-RELATIVE` is non standard (that's what the `X-` indicates). Strictly speaking, that's not a valid `RRULE`.

That said, we use [python-dateutil](https://dateutil.readthedocs.io/en/stable/) to parse `RRULE`s (eg: `todoman` doesn't do the actual parsing, so you should request support for this kind of rule there.

**Comment by Konfekt** [comment]
Thank you. Could this error be handled more gracefully then? Something like a warning that a non-standard keyvalue is used? At least if the field, such as `RRULE`, is ignored anyway?
