### ISSUE TITLE
New todo 

### ISSUE THREAD

**Issue by beli3ver** [pimutils/todoman#48]
Hi

I think you should change the terminal output by the command "todo new" from

```
Usage: todo new [options] [summary]
```
to
```
Usage: todo new [options: --list [list number]] [summary]
``

**Comment by beli3ver** [comment]
Maybe also more information in the docs, how to create new tabs with date, alert , priority and some stuff like that

**Comment by untitaker** [comment]
The options are documented right below when you type `todo new --help`, but not if you type `todo new`. We should hint at the help page when invoking `todo new`.

**Comment by beli3ver** [comment]
That would be create 

Am 15. Oktober 2016 12:30:58 MESZ, schrieb Markus Unterwaditzer <notifications@github.com>:
>The options are documented right below when you type `todo new --help`,
>but not if you type `todo new`. We should hint at the help page when
>invoking `todo new`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pimutils/todoman/issues/48#issuecomment-253975955

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by untitaker** [comment]
You can get the entire docs for `todo new` using `todo new --help` btw, if that was unclear. So you don't have to wait for anything.
