### ISSUE TITLE
Can't confirm installation - Fedora 36

### ISSUE THREAD

**Issue by fdoxgit** [pimutils/todoman#513]
After update, tried to install on Fedora 36.

sudo dnf install todoman
Error: Unable to find a match: todoman

After confirming that Python3 is running version 3.10.9, I tried to install via PIP:

pip install todoman

Everything seems fine, but when I check for the version...

todoman --version
bash: todoman: command not found...

Also, when setting up the configuration file (Home / .local / lib / python3.10 / site-packages / todoman / configuration.py), I'm not sure what to do. The sample configuration file on todoman.readthedocs.io is remarkably simpler than the default configuration file. Do I create a new config.py file in addition to the configuration.py file?

Sorry for the basic questions. I really want to use todoman and I'm hitting my threshold of understanding. Thank you in advance for any help.

**Comment by WhyNotHugo** [comment]
The command is "todo". Eg:

todo --version

**Comment by fdoxgit** [comment]
Thank you
