### ISSUE TITLE
missing 4.2.0 source tarball in pypi

### ISSUE THREAD

**Issue by chenrui333** [pimutils/todoman#519]
It looks like only wheel got published into pypi. Thanks!
![image](https://user-images.githubusercontent.com/1580956/227571115-9febd854-2a44-4650-aeec-0b57d50b6ddc.png)

**Comment by dvzrv** [comment]
Hi! Packaging this for Arch Linux, I was just about to raise this as well :)

**Comment by WhyNotHugo** [comment]
Ack, I’ve revised the publishing script and indeed it only produces wheels. I’ll push 4.2.1 when I get a chance.

**Comment by WhyNotHugo** [comment]
Fixed in 4.2.1.

**Comment by WhyNotHugo** [comment]
Odd, CI logs indicated that the files were uploaded but they're not showing up on PyPI.

**Comment by WhyNotHugo** [comment]
They're now available!
