### ISSUE TITLE
Please release 4.4.0 at PyPi

### ISSUE THREAD

**Issue by Tonus1** [pimutils/todoman#545]
Hi,

As you stated elsewhere, the GH generated sources (tar.gz tagged files) do not let build, metadata are missing.

I haven't found the last 4.4.0 on PyPi and couldn't make a working SlackBuild for this version yet.

Since the previous version has dirty patches to make it run, a new version would be great.

Regards

**Comment by WhyNotHugo** [comment]
Done

**Comment by WhyNotHugo** [comment]
https://pypi.org/project/todoman/4.4.0/
