### ISSUE TITLE
Please provide Changelog/NEWS file

### ISSUE THREAD

**Issue by 0-wiz-0** [pimutils/todoman#55]
Please include a NEWS file into the distribution, so packagers (and users) can easily see what the important changes in the release were.

**Comment by hobarrera** [comment]
Do you need to track new/dropped dependencies? If so, I can tag packagers whenever we have any such change.

If you'd like detailed information about changes in a certain version, then something like this should provide the necessary information:

    git log --no-merges --oneline v1.6.3..v1.7.0 | cut -d ' ' -f2-

**Comment by 0-wiz-0** [comment]
To know about new/dropped dependencies is definitely good.

The `git log` line you mention is something else -- that's a list of all commits.
A `NEWS` file is higher-level -- it groups interesting changes at a user- or developer-level.

**Comment by hobarrera** [comment]
I'll try to include new/dropped dependencies in release tags, would that be okay?

**Comment by 0-wiz-0** [comment]
That'd be good, but please also mention stuff like:
"This release adds support for the FOO tag."
"This release fixes a serious bug in the handling of BAR."
"This release removes support for the obsolete BAZ tag."

**Comment by hobarrera** [comment]
Providing `docs/changelog.rst`, which will also be built/published as part of the documentation.

**Comment by untitaker** [comment]
Can we move this file into the root directory? I didn't know it existed. One can use `.. include` directives to inline it into the docs

**Comment by hobarrera** [comment]
I think the only announcement for it was the above comment.

Yes, I'm okay with moving it into `/CHANGELOG.rst` and using an `include`.
