### ISSUE TITLE
Prevent adding a due date automatically

### ISSUE THREAD

**Issue by pfertyk** [pimutils/todoman#69]
I just started using todoman. I noticed that when I create a new task, it has a due date set automatically to now + 24h. Is there an option to disable this feature (other than editing each task and removing the due date manually)?

**Comment by hobarrera** [comment]
This isn't currently supported. I guess we could have a setting `default_due` (in hours, with a default value of 24), which can supress this if the value is 0.

I'm open for PRs for this, can't quite pick it up right now.

**Comment by pfertyk** [comment]
Took me some time, but I think I got it :) The PR has been created, could you please review it?

**Comment by hobarrera** [comment]
Closed via #78
