### ISSUE TITLE
Editing a todo changes its ID

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#85]
Since an edited todo is removed from the cache and re-inserted, it's id changes (but we never have id re-use). Maybe we should avoid this (if possible).

**Comment by untitaker** [comment]
I still have mixed feelings about having persistent IDs. I see one disadvantage (that in my case most IDs are guaranteed to have more than one digit), but no advantages.

**Comment by hobarrera** [comment]
Advantages are that concurrent operations won't change the IDs, which, IMHO, adds a bit of safety:

* In terminal A run `todo`, walk away.
* Open terminal B, run `todo`, close it.
* Some time later, notice terminal A still there, and do something like `todo done 3` based on what you see on-screen.

It might be a bit uncommon, but I kinda like the determinism this adds.

**Comment by untitaker** [comment]
That is fair enough.

**Comment by hobarrera** [comment]
I'm still willing to discuss it, but I honestly, I generally favour determinism.

**Comment by untitaker** [comment]
An easy fix that wouldn't change the nice cache validation flow we have (first expire, then reinsert) would be to directly derive the ID from the UID.

**Comment by hobarrera** [comment]
I don't think we can derive collision-resistant IDs from UIs due to the amount of digits. Consider that we'd need a two/three digit output for every UID that does not collide (think of it as a hash function).

**Comment by untitaker** [comment]
We could throw in lowercase letters into the mix since those are easy to type as well.

Other options would require updating the cache in-place during validation which is somewhat complicated.

**Comment by hobarrera** [comment]
With letters + numbers (35 symbols), and 80 todos in the db, we'd have a 92% change of collision with two digits, and 7% with three digits. With both lowercase and uppercase letters, this goes down to 1% and 0.5% respectively.

These number are a bit high, because a single collision would make `todo` fail.  
I'm also not convinced that the case-insensitivity of the ids will be obvious.

---

To get a better understaning though, what causes the  dislike for persistent ids? Maybe there's an alternate solution to it it.

**Comment by untitaker** [comment]
I dislike persistent IDs precisely because they fill up the space of possible IDs so much. I usually have a few open tasks where most tasks usually have a single-digit ID. With the new behavior, the tasks that I don't care about (done tasks) and will never address by ID again are assigned a low-digit ID as well.

**Comment by hobarrera** [comment]
Ah, I understand, that's really a really valid concern. Let me think if there's another solution. I take it that `todo flush` is not something you're fond of.

**Comment by untitaker** [comment]
I consider `todo flush` to be a performance workaround but it works.

**Comment by hobarrera** [comment]
How would you feel about an `autoflush` setting to auto-delete `done` tasks? Or do you prefer to keep them around?

**Comment by untitaker** [comment]
I personally have no use for them after I'm done, but we shouldn't assume that the user feels about that the same way.

**Comment by hobarrera** [comment]
Right, I meant, `autoflush` with `default=False`.

If this sounds okay to you, I'll prepare a PR, but if you actually want to keep them around, we can go back to brainstorming.

**Comment by untitaker** [comment]
Since flush also wipes the cache I imagine that this slows down everything a lot.

**Comment by hobarrera** [comment]
It does. 😞 

Back to the drawing board it is!
