### ISSUE TITLE
Enum requires python3.4

### ISSUE THREAD

**Issue by benjaminfrank** [pimutils/todoman#9]
I remember you mentioned the enum I used for the delete option requires python 3.4 while you'd like to keep 3.3 compat. I didn't realize enums are that new, we could also use some simple int constants and use them, so python 3.3 should work.

**Comment by hobarrera** [comment]
> I didn't realize enums are that new

Nor did I actually, I only discovered it after running the tests.

I've actually fixed this via 76f279b anyway.

**Comment by benjaminfrank** [comment]
Cool, didn't notice until today that this is the main repo now (makes sense with the pimutils org though...) and missed the new commits
