### ISSUE TITLE
Changing task list path to empty directory doesn't clear cache

### ISSUE THREAD

**Issue by untitaker** [pimutils/todoman#91]
1.  Have a bunch of tasks and a valid cache
2.  Reconfigure todoman to point to a set of empty tasklists
3.  `todo list` still shows old tasklists

I'll have to figure out what's going on there.

**Comment by hobarrera** [comment]
`expire_lists` _should_ cover this. Also not sure what's going on; I'll try to look at this tomorrow.

**Comment by hobarrera** [comment]
That was fast, thanks!
