### ISSUE TITLE
sqlite due comparisons don't consider timezones

### ISSUE THREAD

**Issue by hobarrera** [pimutils/todoman#92]
Since dates are stored as strings in sqlite, timezones aren't taking properly accounted for when comparing datetimes. (this was revealed by df24af89115b02e588ac0112aa9160719621f362)

**Comment by hobarrera** [comment]
Actually, I found the issue and it's not that: the actual issue is that the test is badly written assuming that the current timezone is `CET`.

Still, my code was broken and the above commit exposed it. 😢

**Comment by untitaker** [comment]
Impressed that you found this so quickly! 👍

**Comment by hobarrera** [comment]
Thanks. TBH, I recalled that sqlite had no proper datetime format, but rather stored strings, so I'd assumed it somehow stemmed from there.
